=== anindita5/codes/Course1.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="course_name" type="courseType"/>
    <xs:element name="location" type="locType"/>
    <xs:element name="labno" type="xs:string"/>
    <xs:element name="facultyid" type="xs:string"/>
    <xs:element name="startdate" type="xs:string"/>
	<xs:element name="enddate" type="xs:string"/>
	<xs:element name="Course" type="coursesType"/>
		
		<xs:simpleType name="courseType">
			<xs:restriction base="xs:string">
				<xs:enumeration value="Servlet"/>
				<xs:enumeration value="JSP2.2"/>
				<xs:enumeration value="Windows Programming"/>
				<xs:enumeration value="OOP and UML"/>
				<xs:enumeration value="HTML5"/>
				<xs:enumeration value="Windows Presentation"/>
			</xs:restriction>
		</xs:simpleType>
		
		<xs:simpleType name="locType">
			<xs:restriction base="xs:string">
				<xs:enumeration value="Pune"/>
				<xs:enumeration value="Mumbai"/>
				<xs:enumeration value="Bangalore"/>
            </xs:restriction>
		</xs:simpleType>
		
		<xs:complexType name="coursesType">
            <xs:sequence>
                <xs:element ref="course_name"/>
                <xs:element ref="location"/>
                <xs:element ref="labno"/>
                <xs:element ref="facultyid"/>
				<xs:element ref="startdate"/>
				<xs:element ref="enddate"/>
            </xs:sequence>
			<xs:attribute name="courseid" type="xs:integer" use="required"/>
        </xs:complexType>
        
        <xs:element name="CourseDetails" type="Coursedetailstype"/>
        <xs:complexType name="Coursedetailstype">
            <xs:sequence>
                <xs:element ref="Course" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
</xs:schema>

=== anindita5/codes/course.xml
<?xml version="1.0"?>
<CourseDetails xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="Course1.xsd">

	<Course courseid ="1">
        <course_name>Servlet</course_name>
        <location>Pune</location>
        <labno>F101</labno>
        <facultyid>101</facultyid>
		<startdate>12-Apr-2016</startdate>
		<enddate>14-Apr-2016</enddate>
    </Course>
	
	<Course courseid ="2">
        <course_name>JSP2.2</course_name>
        <location>Pune</location>
        <labno>F102</labno>
        <facultyid>103</facultyid>
		<startdate>5-Oct-2016</startdate>
		<enddate>8-Oct-2016</enddate>
    </Course>
	
	<Course courseid ="3">
        <course_name>Windows Programming</course_name>
        <location>Mumbai</location>
        <labno>G103</labno>
        <facultyid>103</facultyid>
		<startdate>2-may-2016</startdate>
		<enddate>8-May-2016</enddate>
    </Course>
	
	<Course courseid ="4">
        <course_name>OOP and UML</course_name>
        <location>Mumbai</location>
        <labno>G101</labno>
        <facultyid>104</facultyid>
		<startdate>3-Apr-2016</startdate>
		<enddate>4-Jan-2016</enddate>
    </Course>
	
	<Course courseid ="5">
        <course_name>HTML5</course_name>
        <location>Bangalore</location>
        <labno>G101</labno>
        <facultyid>104</facultyid>
		<startdate>09-Nov-2016</startdate>
		<enddate>12-Nov-2016</enddate>
    </Course>

	<Course courseid ="6">
        <course_name>Windows Presentation</course_name>
        <location>Bangalore</location>
        <labno>G101</labno>
        <facultyid>104</facultyid>
		<startdate>16-July-2016</startdate>
		<enddate>22-July-2016</enddate>
    </Course>
</CourseDetails>
