=== anindita5/codes/orders.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="OrdersList">
    <xs:complexType>
	
      <xs:sequence>
	  
        <xs:element name="Order" maxOccurs="unbounded" minOccurs="0">
		
          <xs:complexType>
		  
            <xs:sequence>
			
              <xs:element type="xs:string" name="pname">   
			  
              </xs:element>
			  
              <xs:element type="xs:integer" name="Qty"/>
			  
              <xs:element type="xs:integer" name="Price"/>
			  
              <xs:element type="xs:integer" name="CustId"/>
			  
            </xs:sequence>
			
            <xs:attribute type="xs:string" name="OrderId" use="optional"/>
			
          </xs:complexType>
		  
        </xs:element>
		
      </xs:sequence>
	  
    </xs:complexType>
	
  </xs:element>
  
</xs:schema>

=== anindita5/codes/orders.xml
<?xml version="1.0"?>

<OrdersList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="Orders.xsd"> 

    <Order OrderId="OR001">                      <!--THIS IS ATTRIBUTE-->
           <pname>Laptop</pname>
           <Qty>4</Qty>
           <Price>3000</Price>
           <CustId>1001</CustId>
    </Order> 
    
     <Order OrderId="OR002">                      <!--THIS IS ATTRIBUTE-->
           <pname>Mobile</pname>
           <Qty>1</Qty>
           <Price>4000</Price>
           <CustId>1001</CustId>
    </Order> 
    
     <Order OrderId="OR003">                      <!--THIS IS ATTRIBUTE-->
           <pname>Cosmetics</pname>
           <Qty>2</Qty>
           <Price>8000</Price>
           <CustId>1001</CustId>
    </Order> 
    
     <Order OrderId="OR004">                      <!--THIS IS ATTRIBUTE-->
           <pname>Cosmetics</pname>
           <Qty>2</Qty>
           <Price>2000</Price>
           <CustId>1003</CustId>
    </Order> 
    
     <Order OrderId="OR005">                      <!--THIS IS ATTRIBUTE-->
           <pname>Mobile</pname>
           <Qty>4</Qty>
           <Price>6000</Price>
           <CustId>1003</CustId>
    </Order> 
    
     <Order OrderId="OR006">                      <!--THIS IS ATTRIBUTE-->
           <pname>USB Cable</pname>
           <Qty>2</Qty>
           <Price>600</Price>
           <CustId>1002</CustId>
    </Order> 
    
     <Order OrderId="OR007">                      <!--THIS IS ATTRIBUTE-->
           <pname>USB CABLE</pname>
           <Qty>4</Qty>
           <Price>600</Price>
           <CustId>1003</CustId>
    </Order>
    
</OrdersList>
